# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Users
guest = User.create(username: "Guest", password: "password", email: "email@email.com")
michael = User.create(username: "aelho_pak", password: "password", email: "michael@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040433/p19_ljgqnx.jpg")
benjamin = User.create(username: "quarks0", password: "2malfor9", email: "benjamin@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040434/prof_3_kxpykt.jpg")
connor = User.create(username: "monnorcurphy", password: "password", email: "connor@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040432/p8_wgbvdv.jpg")
lawrence = User.create(username: "lawrence_c", password: "password", email: "lawrence@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040432/p9_xlltat.jpg")
zero = User.create(username: "aldnoah_zero", password: "password", email: "zero@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040433/p17_vvh978.jpg")
michelle = User.create(username: "michelle_l", password: "password", email: "michelle@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040433/p14_l4qur8.jpg")
sandman = User.create(username: "the_sandman", password: "password", email: "sandman@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040432/p6_szjvsb.jpg")
albert = User.create(username: "albert", password: "password", email: "albert@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040432/p3_l2xddb.jpg")
henry = User.create(username: "nomzly", password: "password", email: "henry@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040432/p4_pkfb05.jpg")
jaimie = User.create(username: "jamallama", password: "password", email: "jaimie@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040433/p13_g91nwq.jpg")
max = User.create(username: "maximillian", password: "password", email: "max@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040432/p5_gnhfjp.jpg")
shaurya = User.create(username: "steelbunz", password: "password", email: "shaurya@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040433/p12_tvwoi8.jpg")
emi = User.create(username: "jet718", password: "password", email: "emi@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040433/p11_dwhawl.jpg")
sena = User.create(username: "serenahyena", password: "password", email: "sena@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040433/p16_ypqqpa.jpg")
minna = User.create(username: "mhsia", password: "password", email: "minna@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040433/p18_tkw39a.jpg")
david = User.create(username: "babi", password: "password", email: "david@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487039620/prof_2_xzma0n.jpg")
jean = User.create(username: "jean", password: "password", email: "jean@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040433/p15_qtc1rz.jpg")
lance = User.create(username: "sirlancelot", password: "password", email: "lance@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040432/p1_fvg5je.jpg")
kiki_jiji = User.create(username: "kiki+jiji", password: "password", email: "kiki+jiji@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040434/p20_rnd9ly.jpg")
parametra = User.create(username: "parametra", password: "password", email: "parametra@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040432/p7_jah0w1.jpg")
igor_oussenko = User.create(username: "igor_o", password: "password", email: "igor@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040432/p2_zsogzs.jpg")
tania_kezha = User.create(username: "tania", password: "password", email: "tania@email.com", image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487040488/prof_23_ewk26a.jpg")

# Photos
photo_1 = Post.create(image_url: "https://res.cloudinary.com/dfrrpfeus/image/upload/v1478216466/seed_photo_1_k3agfk.jpg", caption: "pool lighting at dusk", user_id: 3)
photo_2 = Post.create(image_url: "https://res.cloudinary.com/dfrrpfeus/image/upload/v1478380772/seed_photo_07_gknun8.jpg", caption: "chinese typography project", user_id: 5)
photo_3 = Post.create(image_url: "https://res.cloudinary.com/dfrrpfeus/image/upload/v1478380771/seed_photo_08_lsl9wg.jpg", caption: "ARTIFICIAL branding project", user_id: 5)
photo_4 = Post.create(image_url: "https://res.cloudinary.com/dfrrpfeus/image/upload/v1478380750/seed_photo_04_zg6btw.jpg", caption: "red chinese typography", user_id: 5)
photo_5 = Post.create(image_url: 'https://res.cloudinary.com/dfrrpfeus/image/upload/v1478893612/seed_photo_2_zh74zw.jpg', caption: 'azure tonic water labeling', user_id: 8)
photo_6 = Post.create(image_url: 'https://res.cloudinary.com/dfrrpfeus/image/upload/v1478893612/seed_photo_03_tlzbbc.jpg', caption: 'working on some magazine layouts; thoughts?', user_id: 9)
photo_7 = Post.create(image_url: 'https://res.cloudinary.com/dfrrpfeus/image/upload/v1478893609/seed_photo_05_dclqg4.png', caption: "cute little bear icons i've been working on", user_id: 11)
photo_8 = Post.create(image_url: 'http://res.cloudinary.com/dfrrpfeus/image/upload/v1478893617/seed_photo_06_ut6zbl.jpg', caption: 'silver brush', user_id: 2)
photo_9 = Post.create(image_url: 'https://res.cloudinary.com/dfrrpfeus/image/upload/v1478893613/seed_photo_09_wixvlw.jpg' , caption: 'float', user_id: 14)
photo_10 = Post.create(image_url: 'http://res.cloudinary.com/dfrrpfeus/image/upload/v1478893670/seed_photo_10_lq0fgh.png', caption: 'texture exploration', user_id: 10)
# photo_10_5 = Post.create(image_url: 'http://res.cloudinary.com/dfrrpfeus/image/upload/v1478893673/seed_photo_11_kxbirz.png', caption: 'man in cultural dress with flowers', user_id: 10)
photo_11 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034443/1_vwueun.jpg", user_id: 23, caption: "BALANCE")
photo_12 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034445/2_irhbmz.jpg", user_id: 23, caption: "embelisshed coral bomber mixed with maroon hints")
photo_13 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034442/6_gjfbav.jpg", user_id: 20, caption: "jiji chose this colour! what do you guys think?")
photo_14 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034443/7_b5vh0j.jpg", user_id: 20, caption: "business card design front & back")
photo_15 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034444/8_f9eg5t.jpg", user_id: 6, caption: "floral illustration 2014")
photo_16 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034448/14_ej7h0h.jpg", user_id: 21, caption: "begining project terra de flora")
photo_17 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034444/4_z7rjyk.jpg", user_id: 22, caption: "sheer bloom")
photo_18 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487035141/15_ujefx1.jpg", user_id: 9, caption: "kozlowski branding")
photo_19 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034445/5_zmsr3r.jpg", user_id: 22, caption: "underground magazine grunge")
photo_20 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034444/9_g9ylzr.png", user_id: 13, caption: "re:Scan chrome extension screencap; thoughts?")
photo_21 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034446/11_krwklq.jpg", user_id: 21, caption: "terra de flora: flowers in envelope")
photo_22 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034447/12_v7qqfh.jpg", user_id: 21, caption: "terra de flora: with florals shot")
photo_23 = Post.create(image_url: "http://res.cloudinary.com/dfrrpfeus/image/upload/v1487034447/13_jvyhix.jpg", user_id: 21, caption: "terra de flora: with greens shot")

# comments
comment_1 = Comment.create(user_id: 4, post_id: 1, body: "the lighting so so cool here!")
comment_2 = Comment.create(user_id: 5, post_id: 1, body: "is that girl holding a stop sign?")
comment_3 = Comment.create(user_id: 6, post_id: 1, body: "pretty sure that is just the silhouette of something lol")
comment_4 = Comment.create(user_id: 7, post_id: 2, body: "hey i didn't know you speak/read/write chinese!")
comment_5 = Comment.create(user_id: 2, post_id: 2, body: "me neither! this is really cool; maybe you can help me with some chinese branding")
comment_6 = Comment.create(user_id: 8, post_id: 2, body: "not bad, i like that shade of red")
comment_7 = Comment.create(user_id: 20, post_id: 3, body: "what is ARTIFICIAL?")
comment_8 = Comment.create(user_id: 21, post_id: 3, body: "is this real life? or ARTIFICIAL life?")
comment_9 = Comment.create(user_id: 8, post_id: 3, body: "omg please stop")
comment_10 = Comment.create(user_id: 19, post_id: 4, body: "do you do any work with any other languages?")
comment_11 = Comment.create(user_id: 22, post_id: 4, body: "echoing above commenter")
comment_12 = Comment.create(user_id: 7, post_id: 4, body: "i've never thought to work with chinese before!")
comment_13 = Comment.create(user_id: 9, post_id: 4, body: "i can speak chinese, but can't read or write :( what does this say?")
comment_14 = Comment.create(user_id: 11, post_id: 5, body: "is this for drinking water or facial water?")
comment_15 = Comment.create(user_id: 12, post_id: 5, body: "wow, loving the typography on these")
comment_16 = Comment.create(user_id: 16, post_id: 6, body: "seems really black and white")
comment_17 = Comment.create(user_id: 18, post_id: 6, body: "i like the minimalism of it")
comment_18 = Comment.create(user_id: 19, post_id: 7, body: "aww these are adorable")
comment_19 = Comment.create(user_id: 14, post_id: 7, body: "you should make these into stickers!")
comment_20 = Comment.create(user_id: 15, post_id: 7, body: "i would totally buy these if they were in a sticker store")
comment_21 = Comment.create(user_id: 16, post_id: 8, body: "what is brush used for")
comment_22 = Comment.create(user_id: 17, post_id: 9, body: "is the model merely jumping for this photo or was he photoshopped in?")
comment_23 = Comment.create(user_id: 2, post_id: 10, body: "ooh very nice")
comment_24 = Comment.create(user_id: 4, post_id: 10, body: "wow this is amazing")
comment_25 = Comment.create(user_id: 8, post_id: 11, body: "loving this orange color!")
comment_26 = Comment.create(user_id: 10, post_id: 11, body: "the use of complementary colours in this is on point")
comment_27 = Comment.create(user_id: 14, post_id: 11, body: "who is the model?")
comment_28 = Comment.create(user_id: 8, post_id: 12, body: "love it!")
comment_29 = Comment.create(user_id: 18, post_id: 12, body: "hm, i would have never thought to mix coral/orange with maroon")
comment_29 = Comment.create(user_id: 6, post_id: 12, body: "really liking the tiger embellishment")
comment_29 = Comment.create(user_id: 3, post_id: 13, body: "surprised that jiji went for such a bright color!")
comment_29 = Comment.create(user_id: 2, post_id: 13, body: "same although maybe he took inspiration from your bow?")
comment_29 = Comment.create(user_id: 6, post_id: 13, body: "that being said, i would have thougt it would be black with a bright color pop, not white")
comment_29 = Comment.create(user_id: 1, post_id: 14, body: "it looks good! are these for your mom?")
comment_29 = Comment.create(user_id: 9, post_id: 14, body: "aw kiki, this is great!")
comment_29 = Comment.create(user_id: 12, post_id: 15, body: "when did you draw this?")
comment_29 = Comment.create(user_id: 6, post_id: 15, body: "this was back in high school :)")
comment_29 = Comment.create(user_id: 13, post_id: 16, body: "looking forward to more photos")
comment_29 = Comment.create(user_id: 3, post_id: 17, body: "sheer indeed")
comment_29 = Comment.create(user_id: 6, post_id: 17, body: "are those cherry blossoms?")
comment_29 = Comment.create(user_id: 1, post_id: 18, body: "really liking the typography on this")
comment_29 = Comment.create(user_id: 11, post_id: 19, body: "love her outfit")
comment_29 = Comment.create(user_id: 12, post_id: 20, body: "what does the chrome extension do?")
comment_29 = Comment.create(user_id: 6, post_id: 20, body: "it scans resumes and job descriptions and produces a similarity score and suggests words to increase said score")
comment_29 = Comment.create(user_id: 15, post_id: 21, body: "those are some fancy scissors! do they work?")
comment_29 = Comment.create(user_id: 4, post_id: 21, body: "love this concept")
comment_29 = Comment.create(user_id: 1, post_id: 22, body: "flowers in the mail, how clever!")
comment_29 = Comment.create(user_id: 9, post_id: 22, body: "this is a beautiful color combination")
comment_29 = Comment.create(user_id: 14, post_id: 22, body: "wouldn't mind these showing up on my doorstep")
comment_29 = Comment.create(user_id: 13, post_id: 23, body: "interesting choice to leave out florals")
comment_29 = Comment.create(user_id: 12, post_id: 23, body: "i almost like these more than the photo with flowers")
comment_30 = Comment.create(user_id: 20, post_id: 23, body: "maybe i could help deliver these flower boxes!")

# Likes
like_1 = Like.create(user_id: 1, post_id: 1)
like_2 = Like.create(user_id: 2, post_id: 1)
like_3 = Like.create(user_id: 3, post_id: 1)
like_4 = Like.create(user_id: 4, post_id: 1)
like_5 = Like.create(user_id: 5, post_id: 1)
like_6 = Like.create(user_id: 6, post_id: 1)
like_7 = Like.create(user_id: 7, post_id: 1)
like_8 = Like.create(user_id: 8, post_id: 1)
like_9 = Like.create(user_id: 9, post_id: 1)
like_10 = Like.create(user_id: 10, post_id: 2)
like_11 = Like.create(user_id: 11, post_id: 2)
like_12 = Like.create(user_id: 12, post_id: 2)
like_13 = Like.create(user_id: 13, post_id: 2)
like_14 = Like.create(user_id: 14, post_id: 2)
like_15 = Like.create(user_id: 15, post_id: 2)
like_16 = Like.create(user_id: 16, post_id: 3)
like_17 = Like.create(user_id: 17, post_id: 3)
like_18 = Like.create(user_id: 18, post_id: 3)
like_19 = Like.create(user_id: 19, post_id: 3)
like_20 = Like.create(user_id: 20, post_id: 4)
like_21 = Like.create(user_id: 21, post_id: 4)
like_22 = Like.create(user_id: 22, post_id: 4)
like_23 = Like.create(user_id: 23, post_id: 4)
like_24 = Like.create(user_id: 22, post_id: 4)
like_25 = Like.create(user_id: 21, post_id: 4)
like_26 = Like.create(user_id: 20, post_id: 5)
like_27 = Like.create(user_id: 19, post_id: 5)
like_28 = Like.create(user_id: 18, post_id: 6)
like_29 = Like.create(user_id: 17, post_id: 6)
like_30 = Like.create(user_id: 16, post_id: 6)
like_36 = Like.create(user_id: 15, post_id: 7)
like_32 = Like.create(user_id: 14, post_id: 7)
like_33 = Like.create(user_id: 13, post_id: 7)
like_37 = Like.create(user_id: 12, post_id: 8)
like_35 = Like.create(user_id: 10, post_id: 8)
like_36 = Like.create(user_id: 9, post_id: 8)
like_37 = Like.create(user_id: 8, post_id: 8)
like_38 = Like.create(user_id: 7, post_id: 8)
like_39 = Like.create(user_id: 6, post_id: 9)
like_40 = Like.create(user_id: 5, post_id: 9)
like_41 = Like.create(user_id: 4, post_id: 9)
like_42 = Like.create(user_id: 3, post_id: 9)
like_43 = Like.create(user_id: 2, post_id: 9)
like_44 = Like.create(user_id: 1, post_id: 9)
like_45 = Like.create(user_id: 2, post_id: 10)
like_46 = Like.create(user_id: 3, post_id: 10)
like_47 = Like.create(user_id: 4, post_id: 10)
like_48 = Like.create(user_id: 5, post_id: 11)
like_49 = Like.create(user_id: 6, post_id: 11)
like_50 = Like.create(user_id: 7, post_id: 12)
like_51 = Like.create(user_id: 8, post_id: 12)
like_52 = Like.create(user_id: 9, post_id: 12)
like_53 = Like.create(user_id: 10, post_id: 14)
like_54 = Like.create(user_id: 11, post_id: 14)
like_55 = Like.create(user_id: 12, post_id: 14)
like_56 = Like.create(user_id: 13, post_id: 14)
like_57 = Like.create(user_id: 14, post_id: 14)
like_58 = Like.create(user_id: 15, post_id: 15)
like_59 = Like.create(user_id: 16, post_id: 15)
like_60 = Like.create(user_id: 17, post_id: 16)
like_61 = Like.create(user_id: 18, post_id: 16)
like_62 = Like.create(user_id: 19, post_id: 17)
like_63 = Like.create(user_id: 20, post_id: 17)
like_64 = Like.create(user_id: 21, post_id: 17)
like_65 = Like.create(user_id: 22, post_id: 18)
like_66 = Like.create(user_id: 23, post_id: 18)
like_67 = Like.create(user_id: 22, post_id: 18)
like_68 = Like.create(user_id: 21, post_id: 18)
like_69 = Like.create(user_id: 20, post_id: 19)
like_70 = Like.create(user_id: 19, post_id: 19)
like_71 = Like.create(user_id: 18, post_id: 19)
like_72 = Like.create(user_id: 17, post_id: 19)
like_73 = Like.create(user_id: 16, post_id: 19)
like_74 = Like.create(user_id: 15, post_id: 20)
like_75 = Like.create(user_id: 14, post_id: 20)
like_76 = Like.create(user_id: 13, post_id: 21)
like_77 = Like.create(user_id: 12, post_id: 21)
like_78 = Like.create(user_id: 11, post_id: 21)
like_79 = Like.create(user_id: 10, post_id: 21)
like_80 = Like.create(user_id: 9, post_id: 22)
like_81 = Like.create(user_id: 8, post_id: 22)
like_82 = Like.create(user_id: 7, post_id: 22)
like_83 = Like.create(user_id: 6, post_id: 22)
like_84 = Like.create(user_id: 5, post_id: 23)
like_85 = Like.create(user_id: 4, post_id: 23)
like_86 = Like.create(user_id: 3, post_id: 23)
like_87 = Like.create(user_id: 2, post_id: 23)
like_88 = Like.create(user_id: 1, post_id: 23)
like_89 = Like.create(user_id: 23, post_id: 23)
like_90 = Like.create(user_id: 22, post_id: 1)
like_91 = Like.create(user_id: 21, post_id: 1)
like_92 = Like.create(user_id: 20, post_id: 2)
like_93 = Like.create(user_id: 19, post_id: 2)
like_94 = Like.create(user_id: 18, post_id: 3)
like_95 = Like.create(user_id: 17, post_id: 3)
like_96 = Like.create(user_id: 16, post_id: 4)
like_97 = Like.create(user_id: 15, post_id: 4)
like_98 = Like.create(user_id: 14, post_id: 5)
like_99 = Like.create(user_id: 13, post_id: 5)
like_100 = Like.create(user_id: 12, post_id: 6)

# Follows
follow_1 = Follow.create(followee_id: 21, follower_id: 1)
follow_2 = Follow.create(followee_id: 22, follower_id: 1)
follow_3 = Follow.create(followee_id: 11, follower_id: 1)
follow_4 = Follow.create(followee_id: 8, follower_id: 1)
follow_5 = Follow.create(followee_id: 6, follower_id: 1)
follow_6 = Follow.create(followee_id: 23, follower_id: 1)
# follow_7 = Follow.create(followee_id: 8, follower_id: 1)
# follow_8 = Follow.create(followee_id: 9, follower_id: 1)
# follow_9 = Follow.create(followee_id: 10, follower_id: 1)
# follow_10 = Follow.create(followee_id: 11, follower_id: 1)
# follow_11 = Follow.create(followee_id: 15, follower_id: 1)
# follow_12 = Follow.create(followee_id: 16, follower_id: 1)
# follow_13 = Follow.create(followee_id: 17, follower_id: 1)
# follow_14 = Follow.create(followee_id: 18, follower_id: 1)
# follow_15 = Follow.create(followee_id: 19, follower_id: 1)
# follow_16 = Follow.create(followee_id: 20, follower_id: 1)
# follow_17 = Follow.create(followee_id: 21, follower_id: 1)
# follow_18 = Follow.create(followee_id: 22, follower_id: 1)
# follow_18 = Follow.create(followee_id: 23, follower_id: 1)

follow_19 = Follow.create(followee_id: 2, follower_id: 3)
follow_20 = Follow.create(followee_id: 2, follower_id: 4)
follow_21 = Follow.create(followee_id: 2, follower_id: 5)
follow_22 = Follow.create(followee_id: 2, follower_id: 6)
follow_23 = Follow.create(followee_id: 2, follower_id: 7)

follow_24 = Follow.create(followee_id: 3, follower_id: 3)
follow_25 = Follow.create(followee_id: 3, follower_id: 5)
follow_26 = Follow.create(followee_id: 3, follower_id: 6)
follow_27 = Follow.create(followee_id: 3, follower_id: 7)
follow_28 = Follow.create(followee_id: 3, follower_id: 8)
follow_29 = Follow.create(followee_id: 3, follower_id: 9)

follow_30 = Follow.create(followee_id: 4, follower_id: 5)
follow_31 = Follow.create(followee_id: 4, follower_id: 6)
follow_32 = Follow.create(followee_id: 4, follower_id: 7)
follow_33 = Follow.create(followee_id: 4, follower_id: 8)

follow_34 = Follow.create(followee_id: 5, follower_id: 6)
follow_35 = Follow.create(followee_id: 5, follower_id: 7)
follow_36 = Follow.create(followee_id: 6, follower_id: 8)
follow_37 = Follow.create(followee_id: 6, follower_id: 9)
follow_38 = Follow.create(followee_id: 6, follower_id: 10)
follow_39 = Follow.create(followee_id: 6, follower_id: 11)
follow_40 = Follow.create(followee_id: 6, follower_id: 12)

follow_41 = Follow.create(followee_id: 7, follower_id: 13)
follow_42 = Follow.create(followee_id: 7, follower_id: 14)
follow_43 = Follow.create(followee_id: 7, follower_id: 15)

follow_44 = Follow.create(followee_id: 8, follower_id: 9)
follow_45 = Follow.create(followee_id: 8, follower_id: 10)
follow_46 = Follow.create(followee_id: 8, follower_id: 11)
follow_47 = Follow.create(followee_id: 8, follower_id: 12)

follow_48 = Follow.create(followee_id: 9, follower_id: 10)
follow_49 = Follow.create(followee_id: 9, follower_id: 11)
follow_50 = Follow.create(followee_id: 9, follower_id: 12)
follow_51 = Follow.create(followee_id: 9, follower_id: 13)

follow_52 = Follow.create(followee_id: 10, follower_id: 11)
follow_53 = Follow.create(followee_id: 10, follower_id: 12)
follow_54 = Follow.create(followee_id: 10, follower_id: 13)

follow_55 = Follow.create(followee_id: 11, follower_id: 12)

follow_56 = Follow.create(followee_id: 12, follower_id: 13)
follow_57 = Follow.create(followee_id: 12, follower_id: 14)
follow_58 = Follow.create(followee_id: 12, follower_id: 15)

follow_59 = Follow.create(followee_id: 13, follower_id: 14)
follow_60 = Follow.create(followee_id: 13, follower_id: 15)
follow_61 = Follow.create(followee_id: 13, follower_id: 16)
follow_62 = Follow.create(followee_id: 13, follower_id: 17)

follow_63 = Follow.create(followee_id: 14, follower_id: 15)
follow_64 = Follow.create(followee_id: 14, follower_id: 16)
follow_65 = Follow.create(followee_id: 14, follower_id: 17)

follow_66 = Follow.create(followee_id: 15, follower_id: 16)
follow_67 = Follow.create(followee_id: 15, follower_id: 17)
follow_68 = Follow.create(followee_id: 15, follower_id: 18)
follow_69 = Follow.create(followee_id: 15, follower_id: 19)

follow_70 = Follow.create(followee_id: 16, follower_id: 17)
follow_71 = Follow.create(followee_id: 16, follower_id: 18)
follow_72 = Follow.create(followee_id: 16, follower_id: 19)
follow_73 = Follow.create(followee_id: 16, follower_id: 20)

follow_74 = Follow.create(followee_id: 17, follower_id: 18)
follow_75 = Follow.create(followee_id: 17, follower_id: 19)
follow_76 = Follow.create(followee_id: 17, follower_id: 20)

follow_77 = Follow.create(followee_id: 18, follower_id: 19)
follow_78 = Follow.create(followee_id: 18, follower_id: 20)
follow_79 = Follow.create(followee_id: 18, follower_id: 21)

follow_80 = Follow.create(followee_id: 19, follower_id: 20)
follow_81 = Follow.create(followee_id: 19, follower_id: 21)
follow_82 = Follow.create(followee_id: 19, follower_id: 22)
follow_83 = Follow.create(followee_id: 19, follower_id: 23)

follow_84 = Follow.create(followee_id: 20, follower_id: 21)
follow_85 = Follow.create(followee_id: 20, follower_id: 22)
follow_86 = Follow.create(followee_id: 20, follower_id: 23)
follow_87 = Follow.create(followee_id: 20, follower_id: 2)
follow_88 = Follow.create(followee_id: 20, follower_id: 3)

follow_89 = Follow.create(followee_id: 21, follower_id: 22)
follow_90 = Follow.create(followee_id: 21, follower_id: 23)
follow_91 = Follow.create(followee_id: 21, follower_id: 2)
follow_92 = Follow.create(followee_id: 21, follower_id: 3)
follow_93 = Follow.create(followee_id: 21, follower_id: 4)

follow_94 = Follow.create(followee_id: 22, follower_id: 23)
follow_95 = Follow.create(followee_id: 22, follower_id: 2)
follow_96 = Follow.create(followee_id: 22, follower_id: 3)
follow_97 = Follow.create(followee_id: 22, follower_id: 4)

follow_98 = Follow.create(followee_id: 23, follower_id: 2)
follow_99 = Follow.create(followee_id: 23, follower_id: 3)
follow_100 = Follow.create(followee_id: 23, follower_id: 4)
follow_101 = Follow.create(followee_id: 23, follower_id: 5)
follow_102 = Follow.create(followee_id: 23, follower_id: 6)
follow_103 = Follow.create(followee_id: 23, follower_id: 7)
follow_104 = Follow.create(followee_id: 23, follower_id: 8)
follow_105 = Follow.create(followee_id: 23, follower_id: 9)

follow_106 = Follow.create(followee_id: 1, follower_id: 2)
follow_107 = Follow.create(followee_id: 1, follower_id: 3)
follow_108 = Follow.create(followee_id: 1, follower_id: 4)
follow_109 = Follow.create(followee_id: 1, follower_id: 5)
follow_110 = Follow.create(followee_id: 1, follower_id: 6)
follow_111 = Follow.create(followee_id: 1, follower_id: 7)
follow_112 = Follow.create(followee_id: 1, follower_id: 8)
follow_113 = Follow.create(followee_id: 1, follower_id: 9)
